

services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: smart_banking_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d smart_banking_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  smartbankadviser:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PG_DATABASE_JDBC_URL: jdbc:postgresql://postgres:5432/smart_banking_db
      PG_DATABASE_USERNAME: root
      PG_DATABASE_PASSWORD: 1
      H2_DATABASE_JDBC_URL: jdbc:h2:file:/data/transaction
    volumes:
      - ./src/main/resources/db/transaction.mv.db:/data/transaction.mv.db

  adviserbot:
    build:
      context: ./AdviserBot
    ports:
      - "8081:8081"
    depends_on:
      - smartbankadviser
    environment:
      SMARTBANK_ADVISER_URL: http://smartbankadviser:8080

volumes:
  postgres_data: